/**
 * ReactPublisher — Page → React component source generator.
 *
 * Converts a Page into a self-contained .tsx file that exports a default
 * React functional component containing the page's JSX tree.
 *
 * Isolation (Constraint #269): MUST NOT import from src/core/publisher/ or src/editor/.
 */

import type { Page, Project } from '../page-tree/types'
import type { IModuleRegistry } from '../module-engine/types'
import { createReactExportCollector, nodeToJsx } from './nodeToJsx'

// ---------------------------------------------------------------------------
// Slug → PascalCase component name
// ---------------------------------------------------------------------------

/**
 * Convert a URL slug into a valid React component name (PascalCase).
 *
 * @example
 * slugToComponentName('about-us')  // → 'AboutUs'
 * slugToComponentName('index')     // → 'Index'
 * slugToComponentName('')          // → 'Page'
 */
export function slugToComponentName(slug: string): string {
  const base = (slug || 'page')
    .replace(/[^a-zA-Z0-9]+([a-zA-Z0-9])/g, (_, c: string) => c.toUpperCase())
    .replace(/^[^a-zA-Z]+/, '') // strip leading non-alpha
    .replace(/^(.)/, (c: string) => c.toUpperCase()) // capitalize first letter
  return base || 'Page'
}

// ---------------------------------------------------------------------------
// Page → component source
// ---------------------------------------------------------------------------

export interface PageComponent {
  /** PascalCase React component name, e.g. "Index", "AboutUs" */
  componentName: string
  /** Full .tsx source file content */
  source: string
  /** Page slug (used for routing) */
  slug: string
}

/**
 * Generate a .tsx source file for a single page.
 *
 * The generated component is a simple default export — no routing, no state,
 * no data fetching. Inline styles carry all visual properties as React style
 * objects (CSS-in-JS without a runtime).
 *
 * @param page      The page to compile to JSX
 * @param project   Full project (used for metadata; currently unused but
 *                  reserved for design-token injection in future iterations)
 * @param registry  Module registry providing toJsx() implementations
 */
export function pageToComponent(
  page: Page,
  project: Project,
  registry: IModuleRegistry,
): PageComponent {
  void project
  const componentName = slugToComponentName(page.slug || page.title)
  const collector = createReactExportCollector()
  const bodyJsx = nodeToJsx(page.rootNodeId, page, registry, collector)

  // Wrap the body in a fragment if it isn't already a single element.
  // nodeToJsx() returns the root node's JSX which is always a single element
  // for the base.root container — wrapping in <> ensures valid TSX regardless.
  const jsxBody = bodyJsx || '<></>'

  const source = [
    `// Auto-generated by Page Builder — do not edit manually.`,
    `// Page: ${JSON.stringify(page.title)}`,
    `import React from 'react'`,
    ...Array.from(collector.imports),
    ``,
    ...Array.from(collector.declarations),
    collector.declarations.size > 0 ? `` : undefined,
    `export default function ${componentName}() {`,
    `  return (`,
    `    ${jsxBody}`,
    `  )`,
    `}`,
    ``,
  ].filter((line): line is string => line !== undefined).join('\n')

  return { componentName, source, slug: page.slug }
}
