/**
 * Files Data Layer — type definitions.
 *
 * Architecture source: Contribution #595 §1.2
 *
 * ProjectFile is stored as a flat array in project.files (parallel to
 * project.pages).  The display-layer tree is derived via buildFileTree()
 * in selectors.ts — the same flat-map reasoning that drives Page.nodes
 * (Decision #309 / Constraint #215).
 *
 * Path invariants are enforced at every write boundary by isSafePath()
 * in pathValidation.ts.
 */

// ---------------------------------------------------------------------------
// ProjectFileType
// ---------------------------------------------------------------------------

export type ProjectFileType =
  | 'component' // src/components/*.tsx — user-authored React components
  | 'script'    // src/scripts/*.ts, src/utils/*.ts, src/hooks/*.ts
  | 'style'     // src/styles/*.css — global CSS
  | 'asset'     // public/* — images, fonts, etc. (binary)
  | 'config'    // package.json, tsconfig.json, vite.config.ts, .env, etc.
  | 'doc'       // README.md, CHANGELOG.md — markdown docs

// ---------------------------------------------------------------------------
// ProjectFile
// ---------------------------------------------------------------------------

export interface ProjectFile {
  /** Unique ID — generated with nanoid() (NOT path; path is mutable on rename) */
  id: string

  /**
   * POSIX-style path relative to project root.
   * Examples: "src/components/MyButton.tsx", "public/logo.png", "package.json"
   * Validated by isSafePath() at every write boundary.
   * Must be unique within project.files[].
   */
  path: string

  type: ProjectFileType

  /**
   * Text content for component/script/style/config/doc (UTF-8).
   * For 'asset' files this is undefined; binary content lives in `blob`.
   */
  content?: string

  /**
   * For 'asset' files only — base64-encoded for IndexedDB persistence.
   * (Blob inside Project would defeat structuredClone equality checks.)
   */
  blob?: { mimeType: string; base64: string }

  /**
   * When true, the file was auto-generated by the scaffold (e.g. package.json,
   * vite.config.ts, src/main.tsx).  Generated files are read-only in the UI
   * until the user "ejects" them (sets ejected: true).
   *
   * Publisher behaviour:
   *   generated=true, ejected=false  → scaffold version emitted, this file skipped
   *   generated=true, ejected=true   → this file emitted (user override, overwrites scaffold)
   *   generated=false (or undefined) → always emitted (user-authored file)
   */
  generated?: boolean

  /**
   * When true, the user has edited a previously-generated file.
   * The publisher emits the user's version instead of the scaffold default.
   * Only meaningful when `generated === true`.
   */
  ejected?: boolean

  createdAt: number
  updatedAt: number
}

// ---------------------------------------------------------------------------
// FileTreeNode — display-layer only, never persisted
// ---------------------------------------------------------------------------

export interface FileTreeNode {
  /** Last path segment — e.g. "components" for a dir, "Button.tsx" for a file */
  name: string

  /**
   * Full path relative to project root.
   * For synthesized directory nodes this is the directory path without trailing slash
   * (e.g. "src/components").
   */
  path: string

  /** true for synthesized directory nodes, false for file leaf nodes */
  isDirectory: boolean

  /** Direct children (sorted alphabetically, directories before files) */
  children: FileTreeNode[]

  /** Present only on file leaf nodes (isDirectory === false) */
  file?: ProjectFile
}
